"""Added foreign keys to RecognizedFace and Alerts

Revision ID: 09408874fb7a
Revises: 9f26eb6be56f
Create Date: 2025-03-10 20:40:09.903863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09408874fb7a'
down_revision = '9f26eb6be56f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'missing_persons', ['person_id'], ['id'])

    with op.batch_alter_table('recognized_faces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'missing_persons', ['person_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognized_faces', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('person_id')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###
