"""Fixed relationship issues

Revision ID: e6bd39fc92cd
Revises: 09408874fb7a
Create Date: 2025-03-10 20:50:24.115306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6bd39fc92cd'
down_revision = '09408874fb7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_alert', type_='foreignkey')

    with op.batch_alter_table('recognized_faces', schema=None) as batch_op:
        batch_op.drop_constraint('fk_person', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognized_faces', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_person', 'missing_persons', ['person_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_alert', 'missing_persons', ['person_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
